# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-10 09:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CAProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeAddress', models.TextField()),
                ('postalAddress', models.TextField()),
                ('pincode', models.PositiveIntegerField()),
                ('regNum', models.PositiveIntegerField(blank=True, null=True)),
                ('caId', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('collegeId', models.AutoField(primary_key=True, serialize=False)),
                ('collegeName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='KYProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('year', models.PositiveSmallIntegerField(choices=[(None, 'year'), (1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth')])),
                ('mobile_number', models.BigIntegerField()),
                ('kyId', models.CharField(blank=True, max_length=20)),
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='KYusers.College')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='caprofile',
            name='kyprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='KYusers.KYProfile'),
        ),
    ]
